WebApplication1/Models/ErrorViewModel.cs
using System;

namespace WebApplication1.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebApplication1/Models/MealDetailView.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using StudentenMaaltijd.Entity.Entity;

namespace StudentenMaaltijd.Web.Models
{
    public class MealDetailView
    {
        public int MealId { get; set; }
        public string MealName { get; set; }

        public DateTime PreperationTime { get; set; }

        public String Description { get; set; }

        public int MaxAllowedGuests { get; set; }

        public decimal Price { get; set; }

        public IEnumerable<Student> Students { get; set; }

        public MealDetailView(Meal meal, IEnumerable<Student> students)
        {
            this.MealId = meal.MealId;
            this.MealName = meal.MealName;
            this.Description = meal.Description;
            this.MaxAllowedGuests = meal.MaxAllowedGuests;
            this.Price = meal.Price;
            this.Students = students;
        }
    }
}

WebApplication1/Models/ViewModels/ErrorViewModel.cs
using System;

namespace StudentenMaaltijd.Web.Models.ViewModels
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebApplication1/Controllers/AccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using StudentenMaaltijd.Entity.Entity;
using StudentenMaaltijd.Entity.Entity.Identity;
using StudentenMaaltijd.Entity.Repository;

namespace StudentenMaaltijd.Web.Controllers
{
    public class AccountController : Controller
    { 
        private UserManager<IdentityUser> userManager;
        private SignInManager<IdentityUser> signInManager;
        private IStudentRepository studentRepository;

        public AccountController(UserManager<IdentityUser> userMgr,
            SignInManager<IdentityUser> signInMgr, IStudentRepository studentRepo)
        {
            userManager = userMgr;
            signInManager = signInMgr;
            studentRepository = studentRepo;

        }



        public ActionResult Register()
        {
            return View("Register");
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Register(RegisterModel model)
        {
            if (ModelState.IsValid)
            {
                IdentityUser user = await userManager.FindByIdAsync(model.Name);
                if (user == null)
                {
                    user = new IdentityUser(model.Email);
                    var result = await userManager.CreateAsync(user, model.Password);
                    if (result.Succeeded)
                    {
                        var student = new Student { StudentName = model.Name, Email = model.Email, PhoneNumber = model.PhoneNumber };
                        studentRepository.AddStudent(student);
                        await signInManager.SignInAsync(user, isPersistent: false);
                        return RedirectToAction("Index", "Home");
                    }
                }
            }

            // If we got this far, something failed, redisplay form   
            return View("Register", model);
        }

        [AllowAnonymous]
        public ViewResult Login()
        {
            return View("Login");
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login(LoginModel loginModel)
        {
            if (ModelState.IsValid)
            {
                IdentityUser user =
                    await userManager.FindByNameAsync(loginModel.Email);
                if (user != null)
                {
                    await signInManager.SignOutAsync();
                    if ((await signInManager.PasswordSignInAsync(user,
                        loginModel.Password, false, false)).Succeeded)
                    {
                        return RedirectToAction("Index", "Home");
                    }
                }
            }
            ModelState.AddModelError("", "Invalid name or password");
            return View(loginModel);
        }
        public async Task<RedirectResult> Logout(string returnUrl = "/")
        {
            await signInManager.SignOutAsync();
            return Redirect(returnUrl);
        }
    }
}

WebApplication1/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace StudentenMaaltijd.Web.Controllers
{
    public class DashboardController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

WebApplication1/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using StudentenMaaltijd.Entity.Repository;
using StudentenMaaltijd.Web.Models.ViewModels;

namespace StudentenMaaltijd.Web.Controllers
{
    public class HomeController : Controller
    {
        private IMealRepository repository;

        public HomeController(IMealRepository repoService)
        {
            repository = repoService;
        }

        public IActionResult Index()
        {
            return View(repository.GetMealsWithinTwoWeeks());
        }
    }
}

WebApplication1/Controllers/MealController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using StudentenMaaltijd.Entity.Entity;
using StudentenMaaltijd.Entity.Repository;
using StudentenMaaltijd.Web.Models;

namespace StudentenMaaltijd.Web.Controllers
{
    public class MealController : Controller
    {
        private IMealRepository repository;
        private MealDetailView mealDetailView;

        public MealController(IMealRepository repoService)
        {
            repository = repoService;
        }

        public ViewResult Index() =>
            View(repository.GetMeals());

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Meal meal)
        {
            try
            {
                repository.AddMeal(meal);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Details(int id)
        {
            MealDetailView view = new MealDetailView(repository.GetMeal(id), repository.GetStudentsMeal(id));
            return View(view);
        }

        public ActionResult Edit(int id)
        {
            return View(repository.GetMeal(id));
        }

        [HttpPost]
        public ActionResult Edit(Meal meal)
        {
            try
            {
                repository.EditMeal(meal);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Delete(int id)
        {
            try
            {
                repository.Delete(id);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

WebApplication1/Controllers/StudentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using StudentenMaaltijd.Entity.Entity;
using StudentenMaaltijd.Entity.Repository;

namespace StudentenMaaltijd.Web.Controllers
{
    public class StudentController : Controller
    {
        private IStudentRepository repository;

        public StudentController(IStudentRepository repoService)
        {
            repository = repoService;
        }

        public ViewResult Index() =>
            View(repository.GetStudents());

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                var student = new Student(){ Email = collection["Email"], PhoneNumber = collection["PhoneNumber"], StudentName = collection["StudentName"]};
                repository.AddStudent(student);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

    }
}

WebApplication1/Views/Dashboard/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

WebApplication1/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

WebApplication1/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

WebApplication1/Views/Home/Index.cshtml
@model IEnumerable<StudentenMaaltijd.Entity.Entity.Meal>
@{
    ViewData["Title"] = "Index";
}

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" asp-href-include="lib/bootstrap/dist/css/*.min.css" />
    <title>Students</title>
</head>
<body>
    @if (Model.Count().Equals(0))
    {
        <h1>Geen maaltijden gevonden voor de komende 2 weken!</h1>
        <a class="btn-link" asp-controller="Meal" asp-action="Create">
            <button class="col-lg-12 btn btn-primary">Voeg een maaltijd toe</button>
        </a>
    }
    else
    {
        <table class="table">
            <thead>
            <tr>
                <th>
                    MaaltijdId
                </th>
                <th>
                    Maaltijd
                </th>
                <th>
                    Datum
                </th>
                <th>
                    Beschrijving
                </th>
                <th>
                    Maximaal aantal gasten
                </th>
                <th>
                    Prijs
                </th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.MealId)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.MealName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PreperationTime)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Description)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.MaxAllowedGuests)
                    </td>
                    <td>
                        € @Html.DisplayFor(modelItem => item.Price)
                    </td>
                </tr>
            }
            </tbody>
        </table>
    }
    
</body>
</html>

WebApplication1/Views/Meal/Create.cshtml
@model StudentenMaaltijd.Entity.Entity.Meal

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Meal</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="MealName" class="control-label">Naam</label>
                <input asp-for="MealName" class="form-control" />
                <span asp-validation-for="MealName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PreperationTime" class="control-label">Datum</label>
                <input asp-for="PreperationTime" class="form-control" TextMode="Date" />
                <span asp-validation-for="PreperationTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label">Beschrijving</label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MaxAllowedGuests" class="control-label">Aantal gasten</label>
                <input asp-for="MaxAllowedGuests" class="form-control" />
                <span asp-validation-for="MaxAllowedGuests" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label">Prijs</label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

WebApplication1/Views/Meal/Details.cshtml
@model MealDetailView

<div>
    <h4>Meal</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.MealId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.MealId)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.MealName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.MealName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PreperationTime)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PreperationTime)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.MaxAllowedGuests)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.MaxAllowedGuests)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>
    </dl>

    <h3>Ingeschreven studenten</h3>
    @if (Model.Students.Count().Equals(0))
    {
        <h5>Er zijn geen studenten ingeschreven voor deze maaltijd.</h5>
    }
    else
    {
        <table class="table">
            <thead>
                <tr>
                    <th>
                        naam
                    </th>
                    <th>
                        email
                    </th>
                    <th>
                        telefoonnummer
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.Students)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.StudentId)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.StudentName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Email)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.PhoneNumber)
                        </td>
                    </tr>
                }
            </table>
    }

    </div>


<div>
    @Html.ActionLink("Edit", "Edit", new {  id = Model.MealId  }) |
    <a asp-action="Index">Back to List</a>
</div>

WebApplication1/Views/Meal/Edit.cshtml
@model StudentenMaaltijd.Entity.Entity.Meal

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Meal</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="MealName" class="control-label">Naam</label>
                <input asp-for="MealName" class="form-control" />
                <span asp-validation-for="MealName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PreperationTime" class="control-label">Datum</label>
                <input asp-for="PreperationTime" class="form-control" TextMode="Date" />
                <span asp-validation-for="PreperationTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label">Beschrijving</label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MaxAllowedGuests" class="control-label">Aantal gasten</label>
                <input asp-for="MaxAllowedGuests" class="form-control" />
                <span asp-validation-for="MaxAllowedGuests" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label">Prijs</label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

WebApplication1/Views/Meal/Index.cshtml
@model IEnumerable<StudentenMaaltijd.Entity.Entity.Meal>

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
               MaaltijdId
            </th>
            <th>
                Maaltijd
            </th>
            <th>
                Datum
            </th>
            <th>
                Beschrijving
            </th>
            <th>
                Maximaal aantal gasten
            </th>
            <th>
                Prijs
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.MealId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MealName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PreperationTime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MaxAllowedGuests)
            </td>
            <td>
                € @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.MealId }) |
                @Html.ActionLink("Details", "Details", new {  id=item.MealId  }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.MealId })
            </td>
        </tr>
}
    </tbody>
</table>

WebApplication1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication1</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">WebApplication1</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - WebApplication1</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

WebApplication1/Views/Student/Create.cshtml
@model StudentenMaaltijd.Entity.Entity.Student

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Student</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="StudentName" class="control-label"></label>
                <input asp-for="StudentName" class="form-control" />
                <span asp-validation-for="StudentName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

WebApplication1/Views/Student/Edit.cshtml
@model StudentenMaaltijd.Entity.Entity.Student

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Student</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="StudentId" class="control-label"></label>
                <input asp-for="StudentId" class="form-control" />
                <span asp-validation-for="StudentId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StudentName" class="control-label"></label>
                <input asp-for="StudentName" class="form-control" />
                <span asp-validation-for="StudentName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

WebApplication1/Views/Student/Index.cshtml
@model IEnumerable<StudentenMaaltijd.Entity.Entity.Student>

@{
    ViewData["Title"] = "ListStudent";
}

<h2>ListStudent</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.StudentId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.StudentName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PhoneNumber)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.StudentId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StudentName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PhoneNumber)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>